version: '2'

services:
  postgres:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: defuser
      POSTGRES_PASS: 123456
      POSTGRES_DB: app-db

  web:
    build: .
    env_file:
      - local.env
    command: pm2-dev processes.json
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
